FROM nginx:latest as production
WORKDIR /app

COPY --from=builder /app/packages/client/dist/ /app/
COPY --from=builder /app/default.conf /etc/nginx/conf.d/default.conf

EXPOSE $CLIENT_PORT
CMD [ "nginx", "-g", "daemon off;" ]
