export enum Routes {
  Index = '/',
  Login = 'login',
  SignUp = 'signup',
  Profile = 'profile',
  ControlRoom = 'controlroom',
  Incidents = 'Incidents',
  IncidentsConfirm = 'IncidentsConfirm',
  Warehouse = 'warehouse',
  Classifier = 'classifier',
  ServiceLevel = 'servicelevel',
  Users = 'users',
  Clients = 'clients',
  NotFounde = '*',
}
